apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-app
  labels:
spec:
  replicas: 1
  template:
    metadata:
      name: sample-app-pod
      labels:
        service: sample-app
    spec:
      containers:
      - name: sample-app
        image: quay.io/leopoldodonnell/sample-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4567
