# Default values for sample-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
netProperties: /etc/net.properties
image:
  repository: quay.io/leopoldodonnell/sample-app
  tag: latest
  pullPolicy: Always
service:
  name: sample-app
  type: NodePort
  externalPort: 80
  internalPort: 4567
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

